UILayer_Presentation/Controllers/EmprunteurController.cs
using Bll_Service.Service;
using Entities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UILayer_Presentation.Controllers
{
    public class EmprunteurController : Controller
    {
    
        private readonly IEmprunteurService es;

        public EmprunteurController(IEmprunteurService ess)
        {
            this.es = ess;
        }



        public ActionResult ListeEmrpunteur()
        {
            List<Emprunteur> listeEmprunteurs =  es.GetAllEmprunteurs();
            
            return View(listeEmprunteurs); 
        }




       
        [HttpGet]
        public ActionResult AjoutEmprunteur()
        {
            return View();
        }

     
        [HttpPost]
        public ActionResult AjoutEmprunteur(Emprunteur emp)
        {
            
            if (string.IsNullOrEmpty(emp.Nom)) 
            {
                
                ModelState.AddModelError("Nom", "Le champs du nom est obligatoire");
            }

            if (string.IsNullOrEmpty(emp.Prenom)) /
            {
                
                ModelState.AddModelError("Prenom", "Le champs du prenom est obligatoire");
            }


            if (string.IsNullOrEmpty(Convert.ToString(emp.AnneeNaissance)) | emp.AnneeNaissance < 1000 ) 
            { 

                ModelState.AddModelError("AnnéeNaissance", "L'année de naissance est obligatoire");
            }

            
            if (ModelState.IsValid)
            {
                int verif = es.AjoutEmprunteur(emp);
                if (verif != 0)
                {
                   
                    return RedirectToAction("ListeEmrpunteur");
                }
                else
                {
                    ViewBag.Msg = "L'ajout est KO!";
                    return View(); 

                }
            }
            
            return View(); 


        }




        public ActionResult FindEmprunteur()
        {
            return View();
        }


 
        [HttpPost]
        public ActionResult FindEmprunteur(int id)
        {
           
            Emprunteur efind = es.GetEmprunteurById(id);
            if (efind != null)
            {
                return View(efind);
            }
            else
            {
                ViewBag.Msg = "L'emprunteur n'existe pas";
                return View();
            }

        }



   

        public ActionResult ModifEmprunteur()
        {
            return View();
        }


       
        [HttpPost]
        public ActionResult ModifEmprunteur(Emprunteur emp)
        {
            int verif = es.ModifEmprunteur(emp);
            if (verif != 0)
            {
               
                return RedirectToAction("ListeEmrpunteur");
            }
            else
            {
                ViewBag.Msg = "La modification a échouée !!!";
                return View();
            }

        }



      
        public ActionResult ModifEmpLink(int id)
        {
          
            var eFind = es.GetEmprunteurById(id);

          
            return View("ModifEmprunteur", eFind);
        }




        

        [HttpGet]
        public ActionResult SuppEmpLink(int id)
        {
            
            int verif = es.SuppEmprunteur(id);

            
            return RedirectToAction("ListeEmrpunteur");
        }





        public ActionResult FindLivreEmp()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ListeLivreEmp(int id)
        {
            List<Livre> listeLivresEmp = es.GetAllLivreEmprunteurId(id);

            return View(listeLivresEmp);
        }

        public ActionResult ListeLivreEmp()
        {
            var emp = (Emprunteur)Session["emprunteurSession1"];
            List<Livre> listeLivresEmp = es.GetAllLivreEmprunteurId(emp.Id);

            return View(listeLivresEmp);
        }



        
        public ActionResult AjoutLivreLink(int id)
        {
           
            var eFind = es.GetEmprunteurById(id);
            Session["emprunteurSession1"] = eFind;

            
            return RedirectToAction("AjoutLivreEmprunteur", "Livre");
        }



        

        public ActionResult SuppLivreLink(int id)
        {
            var eFind = es.GetEmprunteurById(id);
            Session["emprunteurSession2"] = eFind;

            return RedirectToAction("ListeLivresEmprunteur", "Livre");
        }
    }
}

UILayer_Presentation/Views/Emprunteur/AjoutEmprunteur.cshtml
@model Entities.Models.Emprunteur

@{
    ViewBag.Title = "AjoutEmprunteur";
}

<h2>Ajout d'un Emprunteur</h2>
<br />
@using (Html.BeginForm("AjoutEmprunteur", "Emprunteur", FormMethod.Post))
{
    <div class="row mb-3">
        @Html.LabelFor(m => m.Nom, new {@class="col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.Nom, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nom, null, new { style = "color:red" })
        </div>
    </div>

    <div class="row mb-3">
        @Html.LabelFor(m => m.Prenom, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.Prenom, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Prenom, null, new { style = "color:red" })
        </div>
        </div>

    <div class="row mb-3">
        @Html.LabelFor(m => m.AnneeNaissance, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.AnneeNaissance, null, new { type = "number", @class = "form-control" })
            @Html.ValidationMessageFor(m => m.AnneeNaissance, null, new { style = "color:red" })
        </div>
        </div>

    <div class="row mb-3">
        <div class="col-2 offset-2">
            <input type="submit" value="Ajouter" class="btn btn-success" />
        </div>
        </div>

        }

        <br />
        <h3 style="color:red; text-align:center">@ViewBag.Msg</h3>

UILayer_Presentation/Views/Emprunteur/FindEmprunteur.cshtml
@model Entities.Models.Emprunteur
@{
    ViewBag.Title = "FindEmprunteur";
}

<h2>Rechercher un Emprunteur</h2>
<br />


@using (Html.BeginForm("FindEmprunteur", "Emprunteur", FormMethod.Post))
{
    <div class="reow mb-3">
        @Html.Label("Id", "ID: ", new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBox("id", null, new { type = "number", @class = "form-control", required = true })
            <!-- Validation coté client avec Required=true-->
            <!--  Html.ValidationMessageFor(m => m.Nom, null, new { style = "color:red" }) Ceci etait la vamidation coté serveur-->
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-2 offset-2">
            <input type="submit" value="Rechercher" class="btn btn-warning" />
        </div>
        </div>
        }


        <br />
        <br />

        <!-- Model stocke les elements qui sont renvoyés vers la vue à travers l'action du controller. Ici il stocke les infos de l'emprunteur (efind) qui a été renvoyé depuis l'action FindEmprunteur du controller Emprunteur.'-->
        @if (Model != null)
        {
            <!-- 1. Si l'emprunteur est trouvé, il affiche l'emprunteur dans une table-->

            <h2 style="color: red; text-align:center"> Emprunteur trouvé</h2>
            <table class="table table-bordered border-primary">

                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>AnnéeNaissance</th>

                </tr>
                <tr>
                    <td>@Model.Id</td>
                    <td>@Model.Nom</td>
                    <td>@Model.Prenom</td>
                    <td>@Model.AnneeNaissance</td>
                </tr>


            </table>
        }

        <!-- Si l'emprunteur pas trouvé, il affiche le message d'erreur spécifier dans ma methode d'action du controller Etudiant'-->
        <br />
        <h3 style="color: red; text-align:center">@ViewBag.Msg</h3>

UILayer_Presentation/Views/Emprunteur/FindLivreEmp.cshtml
@{
    ViewBag.Title = "FindLivreEmp";
}

<h2>Rechercher les livres d'un Emprunteur</h2>
<br />
@using (Html.BeginForm("ListeLivreEmp", "Emprunteur", FormMethod.Post))
{
    <div class="reow mb-3">
        @Html.Label("Id", "ID: ", new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBox("id", null, new { type = "number", @class = "form-control", required = true })
            <!-- Validation coté client avec Required=true-->
            <!--  Html.ValidationMessageFor(m => m.Nom, null, new { style = "color:red" }) Ceci etait la vamidation coté serveur-->
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-2 offset-2">
            <input type="submit" value="Rechercher" class="btn btn-warning" />
        </div>
        </div>
        }

UILayer_Presentation/Views/Emprunteur/ListeEmrpunteur.cshtml
@{
    ViewBag.Title = "ListeEmrpunteur";
}

<br />
<h2>Liste des Emprunteurs</h2>
<br />
<table class="table table-bordered border-primary">

    <tr>
        <th>ID</th>
        <th>Nom</th>
        <th>Prenom</th>
        <th>AnnéeNaissance</th>
        <th>Opération</th>

    </tr>
   
    @foreach (var emprunteur in Model)
    {
        <tr>
            <td>@emprunteur.Id</td>
            <td>@emprunteur.Nom</td>
            <td>@emprunteur.Prenom</td>
            <td>@emprunteur.AnneeNaissance</td>
           
            <td>
                @Html.ActionLink("Modif Emprunteur", "ModifEmpLink", new { id = emprunteur.Id }, new { style = "font-size: 12px", @class = "btn btn-warning font-size: 10px" })
                @Html.ActionLink("Supp Emprunteur", "SuppEmpLink", new { id = emprunteur.Id }, new { style = "font-size: 12px", @class = "btn btn-danger font-size: 10px" })
                @Html.ActionLink("Ajout Livre", "AjoutLivreLink", new { id = emprunteur.Id }, new { style = "font-size: 12px", @class = "btn btn-success font-size: 10px" })
                @Html.ActionLink("Supp Livre", "SuppLivreLink", new { id = emprunteur.Id }, new { style = "font-size: 12px", @class = "btn btn-danger font-size: 10px" })
            </td>
        </tr>
    }

</table>

UILayer_Presentation/Views/Emprunteur/ListeLivreEmp.cshtml
@model List<Entities.Models.Livre>
@{
    ViewBag.Title = "ListeLivreEmp";
}

<br />
<h2>Liste des livres de l'Emprunteur</h2>
<br />
<table class="table table-bordered border-primary">

    <tr>
        <th>ID</th>
        <th>Auteur</th>
        <th>Titre</th>
        <th>Année</th>
        <th>IdEmprunteur</th>

    </tr>
   
    @foreach (var livre in Model)
    {
        <tr>
            <td>@livre.Id</td>
            <td>@livre.Auteur</td>
            <td>@livre.Titre</td>
            <td>@livre.Annee</td>
            <td>@livre.Emprunteur.Id</td>
        </tr>
    }

</table>

UILayer_Presentation/Views/Emprunteur/ModifEmprunteur.cshtml
@model Entities.Models.Emprunteur
@{
    ViewBag.Title = "ModifEmprunteur";
}

<h2>Modifier un emprunteur</h2>
<br />
@using (Html.BeginForm("ModifEmprunteur", "Emprunteur", FormMethod.Post))
{

    <div class="reow mb-3">
        @Html.LabelFor(m => m.Id, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.Id, null, new { type = "number", @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Id, null, new { style = "color:red" })
        </div>
    </div>

    <div class="reow mb-3">
        @Html.LabelFor(m => m.Nom, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.Nom, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Nom, null, new { style = "color:red" })
        </div>
    </div>

    <div class="reow mb-3">
        @Html.LabelFor(m => m.Prenom, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.Prenom, null, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Prenom, null, new { style = "color:red" })
        </div>
    </div>

    <div class="reow mb-3">
        @Html.LabelFor(m => m.AnneeNaissance, new { @class = "col-sm-2 col-form-label" })
        <div class="form-group col-sm-5">
            @Html.TextBoxFor(m => m.AnneeNaissance, null, new { type = "number", @class = "form-control" })
            @Html.ValidationMessageFor(m => m.AnneeNaissance, null, new { style = "color:red" })
        </div>
    </div>

    <div class="row mb-3">
        <div class="col-2 offset-2">
            <!-- La derniere fois on a utilisé button. On peut aussi utiliser input-->
            <input type="submit" value="Modifier" class="btn btn-secondary" />
        </div>
        </div>

        }

        <br />
        <h3 style="color:red; text-align:center">@ViewBag.Msg</h3>